### ISSUE TITLE
pytorch version for this repo

### ISSUE THREAD

**Issue by beyondhtx** [wlguan/MobileNet-v2-pruning#7]
There's no mention of any packages' version in _Readme.md_. I have used torch 1.0.0 to run these scripts, but got some run time errors and complie time erorrs. I think the reason may be the version of our pytorch or other packages didn't match. Which version of torch did you use?

**Comment by beyondhtx** [comment]
In detail, after running
`python main.py --sr --arch MobileNetV2`
when running 
`python prune.py --arch MobileNetV2 --pruner SlimmingPruner --sr --pruneratio 0.6`
a complie time error occured 
```
Traceback (most recent call last):
  File "prune.py", line 96, in <module>
    pruner.prune()
  File "..../MobileNet-v2-pruning/pruner/slimming.py", line 49, in prune
    b.prunemask = torch.where(mask == 1)[0]
TypeError: where() missing 2 required positional argument: "input", "other"

```

**Comment by beyondhtx** [comment]
torch 1.5 works well
